spring.devtools.restart.enabled: false

spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: create
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect


spring.datasource:
    url: jdbc:postgresql://localhost:5432/customer_db
    username: postgres
    password: postgres

