services:
  pubsub-emulator:
    image: google/cloud-sdk:latest
    volumes:
      - ./setup_pubsub.sh:/setup_pubsub.sh
    entrypoint: [ "/bin/bash", "./setup_pubsub.sh" ]
    environment:
      - CLOUDSDK_CORE_PROJECT=emulator
    ports:
      - "8085:8085"
  postgres:
    image: postgres
    container_name: postgres-charges-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: charges
    ports:
      - "5432:5432"